version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: personal-portfolio
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    command: yarn start
