version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: personal-portfolio
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    entrypoint: ./production.sh
